### ISSUE TITLE
white text on white background in list view double panel

### ISSUE THREAD

**Issue by ramlok0** [mate-desktop/caja#1054]
caja version 1.20.2
in dual panel list view, selected file in inactive panel has white font on white background - screenshot attached

#### Expected behaviour
grey background with white font

#### Actual behaviour
white font on white background

#### Steps to reproduce the behaviour
in dual panel list view selected file in inactive panel has white font on white background - screenshot attached

#### Package version
caja version 1.20.2

#### Linux Distribution
xubuntu 18.4

#### Link to downstream report of your Distribution

![listviewwrongfont](https://user-images.githubusercontent.com/31797308/45584845-fa81ec00-b8da-11e8-9407-268664ec25f4.jpg)

**Comment by lukefromdc** [comment]
Which theme are you using? This sort of thing can be different in every theme

**Comment by ramlok0** [comment]
Theme is GreyBird. 
If I switch view to "Icon view" or "Compact view" on both panels, selected text is visible on both sides, only when view is "List view" in inactive panel text is white fg on white bg.

**Comment by lukefromdc** [comment]
This is confirmed in Greybird, which I am guessing is using the selected text color with the same background as the default background for a selected but disabled or inactive item in a treeview. I did not see this in any MATE theme, or in Adwaita, or in my own UbuntuStudio_Legacy theme, so this appears to be a Greybird issue. I don't see any obvious way to fix that by hardcoding something in Caja without screwing up other themes.

**Comment by ramlok0** [comment]
Thank you for reply, I tried different themes, I can reproduce with adwaita, numix themes. 
Issue is not reproducible for me with raleigh, adwaita-dark theme. 
So it's theme dependent and can be closed.

**Comment by allencch** [comment]
I have the same issue. This can be resolved by editing `~/.config/gtk-3.0/gtk.css` with the following CSS

```css
.view:selected,
.caja-pathbar .view:selected {
    background-color: #3584e4; /* Selection background color */
    color: #ffffff; /* Selection text color */
}

.view:not(:focus):selected,
.caja-pathbar .view:not(:focus):selected {
    background-color: #d3d7cf; /* Inactive selection background */
    color: #000000; /* Inactive selection text */
}
```
